### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by agnislav** [devbridge/js-unused-exports#7]
Hi!

Thanks for the tool, looks nice and handy.

The only question I've got right now - is it supposed to work with typescript, e.g. via babel-parser configuration? If so, could you share the example config?

Our codebase is being migrated from js to ts, we're somewhere in the middle and have both JS and TS files. It would be great to have a tool that can help us remove all the dead code as soon as it gets dead.

Thanks!

**Comment by tkirda** [comment]
Hi @agnislav, technically it should not be hard to implement typescript support and I was thinking about this option.

I know there is other similar tool for typescript https://github.com/pzavolinsky/ts-unused-exports

Have you tried it?
